### ISSUE TITLE
Doesn't work on Mac OS because of .DS_Store files

### ISSUE THREAD

**Issue by roelvangils** [jonschlinkert/delete-empty#4]
After some experimenting with your plug-in, I found out why I couldn't get it to work: Mac OS automatically adds a hidden .DS_Store file in each folder. When I manually deleted that file from my (otherwise) empty folders, the recursive deletion worked fine. I think it's safe to delete folders even if it contains a hidden .DS_Store file.

(.DS_Store is a file that stores custom attributes of its containing folder, such as the position of icons or the choice of a background image.)

**Comment by jonschlinkert** [comment]
Wow so sorry, I remember seeing this issue and I was confident I replied to it a long time ago. I also think this should have been done differently. I don't think it would work consistently as it's currently written. 

I'll refactor this as soon as I have a chance, to something more like this (I just tested this over the past couple of days locally as I migrated a bunch of data to new hard drives, worked pretty well):

```js

'use strict';

var fs = require('fs');
var path = require('path');
var exists = require('fs-exists-sync');
var del = require('delete');
var ok = require('log-ok');

module.exports = function(cwd) {
  function remove(dir) {
    if (!exists(dir)) return;

    var stat = fs.statSync(dir);
    if (stat && stat.isDirectory() && dir.indexOf(cwd) === 0) {
      var files = fs.readdirSync(dir);

      if (isEmpty(files)) {
        del.sync(dir, {force: true});
        ok('deleted:', dir);
        remove(path.dirname(dir));

      } else {
        files.forEach(function(name) {
          remove(path.join(dir, name));
        });
      }
    }
  }
  return remove(cwd);
};

function isEmpty(files) {
  return files.filter(wanted).length === 0;
}

function wanted(filename) {
  return !isUnwanted(filename);
}

function isUnwanted(filename) {
  return /(?:Thumbs\.db|\.DS_Store)$/i.test(filename);
}
```

But instead of hardcoding the regex/filter function, I'll update that code to allow a filter function as the second argument. same for the async version

**Comment by roelvangils** [comment]
Thanks! Sounds great 👍
